### ISSUE TITLE
Allow to filter by duration

### ISSUE THREAD

**Issue by PalminX** [thoughtgap/arc-data-server#11]
For visualization and analysis, it would be good to have a filter based in timelineItem duration.

Potential uses:
* Search for extremely short timelineItems (might be erroneous)
* Search for all bicycle trips longer than 1 hr

Filter should include possibility to choose minimum duration and/or maximum duration in different formats

**Comment by thoughtgap** [comment]
Here we go... Hope it's enough on minute base?
