### ISSUE TITLE
Filter returned fields

### ISSUE THREAD

**Issue by thoughtgap** [thoughtgap/arc-data-server#13]
Generic endpoints like `/timelineItems/list` should have filterable fields. E.g. `?fields=itemId,activityType,startDate,duration,placeId,placeName`

**Comment by thoughtgap** [comment]
Implemented. [Possible fields are documented in the wiki.](https://github.com/thoughtgap/arc-data-server/wiki/Filterable-fields-for--timelineItems-list)

**Comment by sobri909** [comment]
The wiki article reminds me of a feature/bug that I'm not sure about the value of in Arc. 

There's `hkStepCount` and `stepCount`. The latter comes from the real time CMPedometer, and the former comes from later HealthKit fetches, performed when viewing the timeline (HealthKit can't be queried when the phone is locked). 

I'm not sure why I've left those separate, and not just put the `hkStepCount` value into the `stepCount` field once it's been fetched. Actually, I suspect they're not even separate, and `stepCount` will simply return the `hkStepCount` value, if available. So possibly the separate property being in the JSON is just simply a bug. 

Can anyone think of any value in keeping them separate? If not, I'll remove `hkStepCount` from the JSON. It seems a bit redundant.

**Comment by thoughtgap** [comment]
I have checked `hkStepCount` and `stepCount` on `timelineItem`-Level for all my data. They do either match, or `hkStepCount` is `null`/not set at all. I will discard `hkStepCount` in arc-data-server.
