### ISSUE TITLE
Extraction from Layer1 to Layer2 does not work on Windows

### ISSUE THREAD

**Issue by PalminX** [thoughtgap/arc-data-server#17]
The new implementation of #1 does not work on Windows, because of some issues with the path handling. I will be working on providing a patch.

**Comment by thoughtgap** [comment]
I changed to config file last night, it must now include the ending / or on windows \

**Comment by PalminX** [comment]
There are still some strange issues I think...

**Comment by PalminX** [comment]
In addition, there's a logical error: the extracted files still might be called "2019-03-17 2.json", but the Layer2 regexp only will look for 2019-03-17.json
